[build]
  command = "npm install && npm run build"
  publish = ".output/public"
  node_version = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[env.production]
  NODE_ENV = "production"
